// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rqhqbytqmhgqayoodksy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJxaHFieXRxbWhncWF5b29ka3N5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQyMjA0NTUsImV4cCI6MjA1OTc5NjQ1NX0.oItR-8cQVjez3C7mWhD5RG24_KOqbKSwn8SIRLmataQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);